* Обязательная часть

Будем осуществлять работу с непростым набором данных о состоянии здоровья лошадей, испытывающих кишечные колики.

* Задание 1. Базовое изучение

Изучить представленный набор данных на основе описания его столбцов и выбрать 8 столбцов для дальнейшего изучения (среди них должны быть как числовые, так и категориальные). 

Провести расчет базовых метрик для них, кратко описать результаты.

* Задание 2. 

Работа с выбросами

В выбранных числовых столбцах найти выбросы, выдвинуть гипотезы об их причинах и проинтерпретировать результаты. Принять и обосновать решение о дальнейшей работе с ними.

* Задание 3. 

Работа с пропусками

Рассчитать количество пропусков для всех выбранных столбцов. Принять и обосновать решение о методе работы с пропусками по каждому столбцу, сформировать датафрейм, в котором пропуски будут отсутствовать.

In [10]:
import pandas as pd
import numpy as np

In [11]:
horse = pd.read_csv(r'C:\Users\Urmas\Desktop\Jupyter\test\Statistika\Базовые понятия\horse_data.csv',  names = range(1,29), na_values='?')
# pd.set_option('display.max_columns', None)  # вывод всех столбцов
horse.head()

,1,2,3,4,5,6,7,8,9,10,...,19,20,21,22,23,24,25,26,27,28
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
1,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
2,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,2,0,0,0,1
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
4,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2

In [24]:
# переименуем столбцы из инфо в доп.таблице
list_ = {
            '1': 'Surgery',
            '2': 'Age',
            '3': 'Hospital_Number',
            '4': 'Rectal_temperature',
            '5': 'Pulse',
            '6': 'Respiratory_rate', 
            '7': 'Temperature_of_extremities',
            '8': 'Peripheral_pulse',
            '9': 'Mucous _embranes',
            '10': 'Capillary_refill_time',
            '11': 'Pain',
            '12': 'Peristalsis',
            '13': 'Abdominal_distension',
            '14': 'Nasogastric_tube',
            '15': 'Nasogastric_reflux',
            '16': 'Nasogastric_reflux_PH',
            '17': 'Rectal_examination_feces',
            '18': 'Abdomen',
            '19': 'Packed_cell_volume',
            '20': 'Total_protein',
            '21': 'Abdominocentesis_appearance',
            '22': 'Abdomcentesis_total_protein',
            '23': 'Outcome',
            '24': 'Surgical_lesion?',
            '25': 'Type_of_lesion1',
            '26': 'Type_of_lesion2',
            '27': 'Type_of_lesion3',
            '28': 'Cp_data'
}
names = list(list_.values())
print(names, sep=',')
horse.columns = [names]
horse.head()

['Surgery', 'Age', 'Hospital_Number', 'Rectal_temperature', 'Pulse', 'Respiratory_rate', 'Temperature_of_extremities', 'Peripheral_pulse', 'Mucous _embranes', 'Capillary_refill_time', 'Pain', 'Peristalsis', 'Abdominal_distension', 'Nasogastric_tube', 'Nasogastric_reflux', 'Nasogastric_reflux_PH', 'Rectal_examination_feces', 'Abdomen', 'Packed_cell_volume', 'Total_protein', 'Abdominocentesis_appearance', 'Abdomcentesis_total_protein', 'Outcome', 'Surgical_lesion?', 'Type_of_lesion1', 'Type_of_lesion2', 'Type_of_lesion3', 'Cp_data']

,Surgery,Age,Hospital_Number,Rectal_temperature,Pulse,Respiratory_rate,Temperature_of_extremities,Peripheral_pulse,Mucous _embranes,Capillary_refill_time,...,Packed_cell_volume,Total_protein,Abdominocentesis_appearance,Abdomcentesis_total_protein,Outcome,Surgical_lesion?,Type_of_lesion1,Type_of_lesion2,Type_of_lesion3,Cp_data
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
1,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
2,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,2,0,0,0,1
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
4,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2

In [25]:
# какие колонки оставим для анализа
# № 1, 2, 4, 5, 7, 9, 11, 13
num = [1, 2, 4, 5, 7, 9, 11, 13]

column_index = list(map(lambda x: x-1, num))
print(column_index)

# для инфо - названия искомых столбцов
column_names= list(filter(None, map(lambda x: x if names.index(x) in list(map(lambda x: x-1, num)) else None, names)))
print(column_names)

[0, 1, 3, 4, 6, 8, 10, 12]
['Surgery', 'Age', 'Rectal_temperature', 'Pulse', 'Temperature_of_extremities', 'Mucous _embranes', 'Pain', 'Abdominal_distension']

In [26]:
# сформируем DataFrame из 8-ми столбцов
# третий и четвертый столбец - количественные непрерывные величины
# первый и одиннадцатый  столбец - качественные номинальные значения (ранжирование незначимо)
# второй, пятый, шестой и тринадцатый столбцы - качественные порядковые значения (ранжирование значимо)

horse_analitic = horse.iloc[:, column_index]
horse_analitic.columns = [column_names]
horse_analitic.head()

,Surgery,Age,Rectal_temperature,Pulse,Temperature_of_extremities,Mucous _embranes,Pain,Abdominal_distension
0,2.0,1,38.5,66.0,3.0,NaN,5.0,4.0
1,1.0,1,39.2,88.0,NaN,4.0,3.0,2.0
2,2.0,1,38.3,40.0,1.0,3.0,3.0,1.0
3,1.0,9,39.1,164.0,4.0,6.0,2.0,4.0
4,2.0,1,37.3,104.0,NaN,6.0,NaN,NaN

In [6]:
horse_analitic = horse_analitic.apply(pd.to_numeric)
horse_analitic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   (Surgery,)                     299 non-null    float64
 1   (Age,)                         300 non-null    int64
 2   (Rectal_temperature,)          240 non-null    float64
 3   (Pulse,)                       276 non-null    float64
 4   (Temperature_of_extremities,)  244 non-null    float64
 5   (Mucous _embranes,)            253 non-null    float64
 6   (Pain,)                        245 non-null    float64
 7   (Abdominal_distension,)        244 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 18.9 KB

In [27]:
horse_analitic = horse_analitic.apply(lambda column: pd.to_numeric(column), axis=0)
horse_analitic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   (Surgery,)                     299 non-null    float64
 1   (Age,)                         300 non-null    int64
 2   (Rectal_temperature,)          240 non-null    float64
 3   (Pulse,)                       276 non-null    float64
 4   (Temperature_of_extremities,)  244 non-null    float64
 5   (Mucous _embranes,)            253 non-null    float64
 6   (Pain,)                        245 non-null    float64
 7   (Abdominal_distension,)        244 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 18.9 KB

In [8]:
horse_analitic.describe()

,Surgery,Age,Rectal_temperature,Pulse,Temperature_of_extremities,Mucous _embranes,Pain,Abdominal_distension
count,299.000000,300.000000,240.000000,276.000000,244.000000,253.000000,245.00000,244.000000
mean,1.397993,1.640000,38.167917,71.913043,2.348361,2.853755,2.95102,2.266393
std,0.490305,2.173972,0.732289,28.630557,1.045054,1.620294,1.30794,1.065131
min,1.000000,1.000000,35.400000,30.000000,1.000000,1.000000,1.00000,1.000000
25%,1.000000,1.000000,37.800000,48.000000,1.000000,1.000000,2.00000,1.000000
50%,1.000000,1.000000,38.200000,64.000000,3.000000,3.000000,3.00000,2.000000
75%,2.000000,1.000000,38.500000,88.000000,3.000000,4.000000,4.00000,3.000000
max,2.000000,9.000000,40.800000,184.000000,4.000000,6.000000,5.00000,4.000000

In [29]:
moda_Age = horse_analitic.Age.mode()
moda_Age

TypeError: only integer scalar arrays can be converted to a scalar index

In [22]:
# расчет моды для всего DataFrame
moda = horse_analitic.round().mode()
moda

,Surgery,Age,Rectal_temperature,Pulse,Temperature_of_extremities,Mucous _embranes,Pain,Abdominal_distension
0,1.0,1.0,38.0,48.0,3.0,1.0,3.0,1.0

In [23]:
# расчет моды вручную
moda = {}
for line in horse_analitic.Age.round():
    if line not in moda:
        moda[line] = 1
    else:
        moda[line] += 1
        
max_line = 0
mode = None
for k, v in moda.items():
    if max_line <v:
        max_line = v
        mode = k
print('Значение моды', moda)

TypeError: only integer scalar arrays can be converted to a scalar index

In [31]:
horse_analitic["Age"]

TypeError: only integer scalar arrays can be converted to a scalar index

# Выбросы

In [ ]:
q1 = horse_analitic.Rectal_temperature.quantile(0.25)
q3 = horse_analitic.Rectal_temperature.quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)
remove_outliers = horse_analitic[horse_analitic.Rectal_temperature.between(lower_bound, upper_bound, inclusive=True)].sort_values('Rectal_temperature')
remove_outliers

In [ ]:
q1_2 = horse_analitic.Pulse.quantile(0.25)
q3_2 = horse_analitic.Pulse.quantile(0.75)
iqr_2 = q3_2 - q1_2
lower_bound_2 = q1_2 - (1.5 * iqr_2)
upper_bound_2 = q3_2 + (1.5 * iqr_2)
remove_outliers_2 = horse_analitic[horse_analitic.Pulse.between(lower_bound_2, upper_bound_2, inclusive=True)].sort_values('Pulse')
remove_outliers_2

In [ ]:
# определяем выброс
pd.concat([horse_analitic, remove_outliers, remove_outliers_2]).drop_duplicates(keep=False)

# Пропуски

In [ ]:
# пропуски, количество
horse_analitic.isnull().sum()

In [ ]:
horse_analitic.info()

In [ ]:
# пропуски в %
for col in horse_analitic.columns:
    pct_missing = horse_analitic[col].isnull().mean()
    print(f'{col} - {pct_missing :.1%}')

In [ ]:
horse_analitic.fillna(0, inplace=True)
horse_analitic.head()

In [ ]:
horse_analitic.astype(int)

In [ ]:
moda_Age = horse_analitic.Age.round().mode()[0]

In [ ]:
data = pd.read_csv(r'C:\Users\Urmas\Desktop\Jupyter\test\Statistika\Базовые понятия\horse_data.csv', names=range(1,29), na_values='?')
pd.set_option('display.max_columns', None)  # вывод всех столбцов
data

In [ ]:
data2 = data.iloc[:, [0, 1, 3, 4, 6, 8, 10, 12]]
data2.columns = ['Surgery', 'Age', 'Rectal_temperature', 'Pulse', 'Temperature_of_extremities', 'Mucous _embranes', 'Pain', 'Abdominal_distension']
data2

In [ ]:
data2.fillna(0, inplace=True)
data2.head()