Домашнее задание «Библиотека Pandas»

* Задание 1

Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. 

Определите, какому фильму было выставлено больше всего оценок 5.0.

In [1]:
import pandas as pd

In [2]:
read_file = pd.read_csv(r'C:\Users\Urmas\Desktop\Jupyter\test\Pandas\САЙТ\ratings.csv')
read_file.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [3]:
max_rating_moviId = read_file[read_file.rating == 5.0].groupby(['movieId']).count().sort_values('rating', ascending = False)
max_rating_moviId.head(1)

         userId  rating  timestamp
movieId
318         153     153        153

* Задание 2

По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [4]:
data = pd.read_csv('power.csv')
data.head()

   country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [5]:
baltica = data[((data['country'] == 'Latvia') | (data['country'] == 'Estonia') | (data['country'] == 'Lithuania')) & ((data['category'] == 4) | (data['category'] == 12) | (data['category'] == 21)) & ((data['year'] >= 2005) & (data['year'] <= 2010)) & (data['quantity'] > 0)].quantity.sum()
baltica

240580.0

* Задание 3

Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.

Примеры страниц (необязательно брать именно эти):

https://fortrader.org/quotes

https://www.finanz.ru/valyuty/v-realnom-vremeni

In [6]:
import_table_in_pandas = pd.read_html('https://www.finanz.ru/valyuty/v-realnom-vremeni', encoding = 'utf-8')[1]
import_table_in_pandas.head(40)

,Unnamed: 0,Рубль,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
0,NaN,GBP/RUB,1011907,-,1019185,"-0,71 %",-07278,13:27:00
1,NaN,EUR/RUB,906060,-,907910,"-0,20 %",-01850,13:27:00
2,NaN,USD/RUB,767088,-,770825,"-0,48 %",-03737,13:27:00
3,NaN,JPY/RUB,07282,-,07312,"-0,41 %",-00030,13:27:00
4,NaN,CNY/RUB,115888,-,116228,"-0,29 %",-00341,13:27:00
5,NaN,CHF/RUB,839054,-,840595,"-0,18 %",-01541,13:27:00
6,NaN,Евро,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
7,NaN,EUR/USD,11813,-,11778,"0,30 %",00035,13:26:00
8,NaN,EUR/GBP,08953,-,08908,"0,51 %",00046,13:27:00
9,NaN,EUR/JPY,1244090,-,1241600,"0,20 %",02490,13:27:00
10,NaN,EUR/CHF,10797,-,10801,"-0,04 %",-00004,13:26:00
11,NaN,Доллар США,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
12,NaN,USD/EUR,08466,-,08490,"-0,28 %",-00024,13:27:00
13,NaN,USD/GBP,07581,-,07563,"0,24 %",00018,13:27:00
14,NaN,USD/JPY,1053310,-,1054250,"-0,09 %",-00940,13:27:00
15,NaN,USD/CHF,09140,-,09171,"-0,34 %",-00031,13:26:00
16,NaN,Японская иена,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
17,NaN,JPY/EUR (100:1),08000,-,08100,"-0,21 %",00000,13:27:00
18,NaN,JPY/GBP,00072,-,00072,"0,33 %",00000,13:27:00
19,NaN,JPY/USD,00095,-,00095,"0,09 %",00000,13:27:00
20,NaN,JPY/CHF (100:1),08700,-,08700,"-0,24 %",00000,13:27:00
21,NaN,Фунт стерлингов,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
22,NaN,GBP/USD,13193,-,13223,"-0,23 %",-00030,13:27:00
23,NaN,GBP/JPY,1389303,-,1393916,"-0,33 %",-04614,13:27:00
24,NaN,GBP/EUR,11170,-,11227,"-0,51 %",-00058,13:26:00
25,NaN,GBP/CHF,12060,-,12130,"-0,58 %",-00070,13:26:00
26,NaN,Швейцарский франк,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
27,NaN,GBP/CHF,12060,-,12130,"-0,58 %",-00070,13:26:00
28,NaN,EUR/CHF,10797,-,10801,"-0,04 %",-00004,13:26:00
29,NaN,JPY/CHF (100:1),08700,-,08700,"-0,24 %",00000,13:27:00
30,NaN,USD/CHF,09140,-,09171,"-0,34 %",-00031,13:26:00
31,NaN,Украинская гривна,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
32,NaN,EUR/UAH,333157,-,332168,"0,30 %",00988,13:27:00
33,NaN,USD/UAH,282038,-,282013,"0,01 %",00025,13:25:00
34,NaN,CHF/UAH,308541,-,307538,"0,33 %",01003,13:27:00
35,NaN,GBP/UAH,372036,-,372877,"-0,23 %",-00841,13:27:00

In [11]:
df = pd.read_html('https://www.finanz.ru/valyuty/usd-rub', attrs = {'class': 'news_table'}, encoding='utf-8')
df

[       Дата  Закрытие  Открытие  Максимум  Минимум
 0  11.11.20    770825    766272    772062   760485
 1  10.11.20    766320    762969    769305   761280
 2  09.11.20    763029    774795    775634   757505
 3  08.11.20    773545    775545    775545   772805
 4  06.11.20    776095    768820    779180   766184
 5  05.11.20    767710    775417    787963   767117
 6  04.11.20    775480    791538    799485   774340
 7  03.11.20    791537    805250    806645   790560
 8  02.11.20    805250    794580    809545   794494,
        Имя  Unnamed: 1     %     курс                 Дата
 0  EUR/RUB         NaN -2038    90606  12.11.2020 13:27:00
 1  USD/RUB         NaN -4848   767088  12.11.2020 13:27:00
 2  CHF/RUB         NaN -1833   839054  12.11.2020 13:27:00
 3  JPY/RUB         NaN -4054     7282  12.11.2020 13:27:00
 4  GBP/RUB         NaN -7141  1011907  12.11.2020 13:27:00
 5  NOK/RUB         NaN -4712    84438  12.11.2020 13:27:00
 6  AUD/RUB         NaN -4977   558214  12.11.2020 13:27:00
 7  NZD/RUB         NaN  -513   527761  12.11.2020 13:27:00
 8  TRY/RUB         NaN    46    98925  12.11.2020 13:27:00]

In [10]:
pip install --upgrade lxml

Requirement already up-to-date: lxml in c:\programdata\anaconda3\lib\site-packages (4.6.1)
Note: you may need to restart the kernel to use updated packages.